# Generated by Django 4.0.2 on 2022-02-09 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.PositiveSmallIntegerField(verbose_name='Тонн руды')),
                ('sio2', models.FloatField(default=0.0, verbose_name='SiO2')),
                ('fe', models.FloatField(default=0.0, verbose_name='Fe')),
                ('title', models.CharField(default='Склад 42', max_length=256, unique=True, verbose_name='Наименование')),
                ('polygon', models.CharField(help_text='Mask example: ((4, 4), (4, 6), (6, 6), (6, 4), (4, 4))', max_length=512, verbose_name='Полигон')),
                ('max_mass', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимально (т.)')),
            ],
            options={
                'verbose_name': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.PositiveSmallIntegerField(verbose_name='Тонн руды')),
                ('sio2', models.FloatField(default=0.0, verbose_name='SiO2')),
                ('fe', models.FloatField(default=0.0, verbose_name='Fe')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.cargo', verbose_name='Груз')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'История доставки на склад',
            },
        ),
    ]
