# Generated by Django 4.0.2 on 2022-02-09 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='fe',
        ),
        migrations.RemoveField(
            model_name='history',
            name='mass',
        ),
        migrations.RemoveField(
            model_name='history',
            name='sio2',
        ),
    ]
