# Generated by Django 4.0.2 on 2022-02-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_history_fe_remove_history_mass_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История доставки на склад', 'verbose_name_plural': 'История доставки на склады'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.AddField(
            model_name='history',
            name='coordinates',
            field=models.CharField(blank=True, help_text='Format: x y / x, y / (x, y)', max_length=12, null=True, verbose_name='Координаты разгрузки (x y)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='max_mass',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. грузоподъемность (т)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='polygon',
            field=models.CharField(default='((30 10, 40 40, 20 40, 10 20, 30 10))', help_text='Mask example: ((30 10, 40 40, 20 40, 10 20, 30 10))', max_length=512, verbose_name='Полигон'),
        ),
    ]
