# Generated by Django 4.0.2 on 2022-02-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_history_options_alter_store_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='coordinates',
            field=models.CharField(blank=True, help_text='Format: x y / x, y / (x, y)', max_length=8, null=True, verbose_name='Координаты разгрузки (x y)'),
        ),
    ]
