# Generated by Django 4.0.2 on 2022-02-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0005_alter_mine_options_remove_cargo_coordinates'),
        ('store', '0004_alter_history_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='coordinates',
            field=models.CharField(blank=True, help_text='Format: X Y', max_length=8, null=True, verbose_name='Координаты разгрузки (x y)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='max_mass',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. груз (т)'),
        ),
        migrations.AlterUniqueTogether(
            name='history',
            unique_together={('store', 'cargo')},
        ),
    ]
