# Generated by Django 4.0.2 on 2022-02-09 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Карьер шахта 001', max_length=256, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Шахта',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.PositiveSmallIntegerField(verbose_name='Тонн руды')),
                ('sio2', models.FloatField(default=0.0, verbose_name='SiO2')),
                ('fe', models.FloatField(default=0.0, verbose_name='Fe')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mine.mine', verbose_name='Карьер/шахата')),
                ('tipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipper.tipper', verbose_name='Самосвал/шахата')),
            ],
            options={
                'verbose_name': 'Груз',
            },
        ),
    ]
