# Generated by Django 4.0.2 on 2022-02-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name': 'Груз', 'verbose_name_plural': 'Грузы'},
        ),
        migrations.AddField(
            model_name='cargo',
            name='coordinates',
            field=models.CharField(blank=True, help_text='Format: x, y / (x, y)', max_length=12, null=True, verbose_name='Координаты разгрузки (x y)'),
        ),
    ]
