# Generated by Django 4.0.2 on 2022-02-10 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipper', '0002_alter_tmodel_max_mass'),
        ('mine', '0002_alter_cargo_options_cargo_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='coordinates',
            field=models.CharField(default='0, 0', help_text='Format: x, y / (x, y)', max_length=12, verbose_name='Координаты разгрузки (x y)'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='tipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipper.tipper', verbose_name='Самосвал'),
        ),
    ]
