# Generated by Django 4.0.2 on 2022-02-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0003_alter_cargo_coordinates_alter_cargo_tipper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='coordinates',
            field=models.CharField(blank=True, help_text='Format: x y / x, y / (x, y)', max_length=12, null=True, verbose_name='Координаты разгрузки (x y)'),
        ),
    ]
