# Generated by Django 4.0.2 on 2022-02-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0004_alter_cargo_coordinates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mine',
            options={'verbose_name': 'Шахта', 'verbose_name_plural': 'Шахты'},
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='coordinates',
        ),
    ]
