# Generated by Django 4.0.2 on 2022-02-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmodel',
            name='max_mass',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Макс. грузоподъемность (т.руды)'),
        ),
    ]
