# Generated by Django 4.0.2 on 2022-02-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipper', '0002_alter_tmodel_max_mass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipper',
            options={'verbose_name': 'Самосвал', 'verbose_name_plural': 'Самосвалы'},
        ),
        migrations.AlterModelOptions(
            name='tmodel',
            options={'verbose_name': 'Модель самосвала', 'verbose_name_plural': 'Модели самосвалов'},
        ),
    ]
